// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.structure.proto

package com.innoscripta.common.protos.file.structure;

public final class FileStructureProtos {

  private FileStructureProtos() {}

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistryLite registry
  ) {}

  static {}
  // @@protoc_insertion_point(outer_class_scope)
}
