// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.structure.proto

package com.innoscripta.common.protos.file.structure;

/**
 * Protobuf type {@code com.innoscripta.common.FileStructure}
 */
public final class FileStructure
  extends com.google.protobuf.GeneratedMessageLite<FileStructure, FileStructure.Builder>
  implements
    // @@protoc_insertion_point(message_implements:com.innoscripta.common.FileStructure)
    FileStructureOrBuilder {

  private FileStructure() {
    filePath_ = "";
    serializeType_ = "";
    fileContent_ = "";
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;

  /**
   * <code>required uint32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>required uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  /**
   * <code>required uint32 id = 1;</code>
   * @param value The id to set.
   */
  private void setId(int value) {
    bitField0_ |= 0x00000001;
    id_ = value;
  }

  /**
   * <code>required uint32 id = 1;</code>
   */
  private void clearId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    id_ = 0;
  }

  public static final int FILEPATH_FIELD_NUMBER = 2;
  private java.lang.String filePath_;

  /**
   * <code>optional string filePath = 2;</code>
   * @return Whether the filePath field is set.
   */
  @java.lang.Override
  public boolean hasFilePath() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>optional string filePath = 2;</code>
   * @return The filePath.
   */
  @java.lang.Override
  public java.lang.String getFilePath() {
    return filePath_;
  }

  /**
   * <code>optional string filePath = 2;</code>
   * @return The bytes for filePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFilePathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(filePath_);
  }

  /**
   * <code>optional string filePath = 2;</code>
   * @param value The filePath to set.
   */
  private void setFilePath(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
    bitField0_ |= 0x00000002;
    filePath_ = value;
  }

  /**
   * <code>optional string filePath = 2;</code>
   */
  private void clearFilePath() {
    bitField0_ = (bitField0_ & ~0x00000002);
    filePath_ = getDefaultInstance().getFilePath();
  }

  /**
   * <code>optional string filePath = 2;</code>
   * @param value The bytes for filePath to set.
   */
  private void setFilePathBytes(com.google.protobuf.ByteString value) {
    filePath_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int SERIALIZETYPE_FIELD_NUMBER = 3;
  private java.lang.String serializeType_;

  /**
   * <code>optional string serializeType = 3;</code>
   * @return Whether the serializeType field is set.
   */
  @java.lang.Override
  public boolean hasSerializeType() {
    return ((bitField0_ & 0x00000004) != 0);
  }

  /**
   * <code>optional string serializeType = 3;</code>
   * @return The serializeType.
   */
  @java.lang.Override
  public java.lang.String getSerializeType() {
    return serializeType_;
  }

  /**
   * <code>optional string serializeType = 3;</code>
   * @return The bytes for serializeType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSerializeTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serializeType_);
  }

  /**
   * <code>optional string serializeType = 3;</code>
   * @param value The serializeType to set.
   */
  private void setSerializeType(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
    bitField0_ |= 0x00000004;
    serializeType_ = value;
  }

  /**
   * <code>optional string serializeType = 3;</code>
   */
  private void clearSerializeType() {
    bitField0_ = (bitField0_ & ~0x00000004);
    serializeType_ = getDefaultInstance().getSerializeType();
  }

  /**
   * <code>optional string serializeType = 3;</code>
   * @param value The bytes for serializeType to set.
   */
  private void setSerializeTypeBytes(com.google.protobuf.ByteString value) {
    serializeType_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static final int FILECONTENT_FIELD_NUMBER = 4;
  private java.lang.String fileContent_;

  /**
   * <code>optional string fileContent = 4;</code>
   * @return Whether the fileContent field is set.
   */
  @java.lang.Override
  public boolean hasFileContent() {
    return ((bitField0_ & 0x00000008) != 0);
  }

  /**
   * <code>optional string fileContent = 4;</code>
   * @return The fileContent.
   */
  @java.lang.Override
  public java.lang.String getFileContent() {
    return fileContent_;
  }

  /**
   * <code>optional string fileContent = 4;</code>
   * @return The bytes for fileContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFileContentBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fileContent_);
  }

  /**
   * <code>optional string fileContent = 4;</code>
   * @param value The fileContent to set.
   */
  private void setFileContent(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
    bitField0_ |= 0x00000008;
    fileContent_ = value;
  }

  /**
   * <code>optional string fileContent = 4;</code>
   */
  private void clearFileContent() {
    bitField0_ = (bitField0_ & ~0x00000008);
    fileContent_ = getDefaultInstance().getFileContent();
  }

  /**
   * <code>optional string fileContent = 4;</code>
   * @param value The bytes for fileContent to set.
   */
  private void setFileContentBytes(com.google.protobuf.ByteString value) {
    fileContent_ = value.toStringUtf8();
    bitField0_ |= 0x00000008;
  }

  public static final int DATE_CREATED_FIELD_NUMBER = 5;
  private float dateCreated_;

  /**
   * <code>optional float date_created = 5;</code>
   * @return Whether the dateCreated field is set.
   */
  @java.lang.Override
  public boolean hasDateCreated() {
    return ((bitField0_ & 0x00000010) != 0);
  }

  /**
   * <code>optional float date_created = 5;</code>
   * @return The dateCreated.
   */
  @java.lang.Override
  public float getDateCreated() {
    return dateCreated_;
  }

  /**
   * <code>optional float date_created = 5;</code>
   * @param value The dateCreated to set.
   */
  private void setDateCreated(float value) {
    bitField0_ |= 0x00000010;
    dateCreated_ = value;
  }

  /**
   * <code>optional float date_created = 5;</code>
   */
  private void clearDateCreated() {
    bitField0_ = (bitField0_ & ~0x00000010);
    dateCreated_ = 0F;
  }

  public static final int DATE_UPDATED_FIELD_NUMBER = 6;
  private float dateUpdated_;

  /**
   * <code>optional float date_updated = 6;</code>
   * @return Whether the dateUpdated field is set.
   */
  @java.lang.Override
  public boolean hasDateUpdated() {
    return ((bitField0_ & 0x00000020) != 0);
  }

  /**
   * <code>optional float date_updated = 6;</code>
   * @return The dateUpdated.
   */
  @java.lang.Override
  public float getDateUpdated() {
    return dateUpdated_;
  }

  /**
   * <code>optional float date_updated = 6;</code>
   * @param value The dateUpdated to set.
   */
  private void setDateUpdated(float value) {
    bitField0_ |= 0x00000020;
    dateUpdated_ = value;
  }

  /**
   * <code>optional float date_updated = 6;</code>
   */
  private void clearDateUpdated() {
    bitField0_ = (bitField0_ & ~0x00000020);
    dateUpdated_ = 0F;
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    java.nio.ByteBuffer data
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    java.nio.ByteBuffer data,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    com.google.protobuf.ByteString data
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    com.google.protobuf.ByteString data,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    byte[] data
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    byte[] data,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    java.io.InputStream input
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    java.io.InputStream input,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseDelimitedFrom(
    java.io.InputStream input
  ) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseDelimitedFrom(
    java.io.InputStream input,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    com.google.protobuf.CodedInputStream input
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure parseFrom(
    com.google.protobuf.CodedInputStream input,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input,
      extensionRegistry
    );
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(
    com.innoscripta.common.protos.file.structure.FileStructure prototype
  ) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.innoscripta.common.FileStructure}
   */
  public static final class Builder
    extends com.google.protobuf.GeneratedMessageLite.Builder<com.innoscripta.common.protos.file.structure.FileStructure, Builder>
    implements
      // @@protoc_insertion_point(builder_implements:com.innoscripta.common.FileStructure)
      com.innoscripta.common.protos.file.structure.FileStructureOrBuilder {

    // Construct using com.innoscripta.common.protos.file.structure.FileStructure.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return instance.hasId();
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return instance.getId();
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>optional string filePath = 2;</code>
     * @return Whether the filePath field is set.
     */
    @java.lang.Override
    public boolean hasFilePath() {
      return instance.hasFilePath();
    }

    /**
     * <code>optional string filePath = 2;</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      return instance.getFilePath();
    }

    /**
     * <code>optional string filePath = 2;</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFilePathBytes() {
      return instance.getFilePathBytes();
    }

    /**
     * <code>optional string filePath = 2;</code>
     * @param value The filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePath(java.lang.String value) {
      copyOnWrite();
      instance.setFilePath(value);
      return this;
    }

    /**
     * <code>optional string filePath = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilePath() {
      copyOnWrite();
      instance.clearFilePath();
      return this;
    }

    /**
     * <code>optional string filePath = 2;</code>
     * @param value The bytes for filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePathBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFilePathBytes(value);
      return this;
    }

    /**
     * <code>optional string serializeType = 3;</code>
     * @return Whether the serializeType field is set.
     */
    @java.lang.Override
    public boolean hasSerializeType() {
      return instance.hasSerializeType();
    }

    /**
     * <code>optional string serializeType = 3;</code>
     * @return The serializeType.
     */
    @java.lang.Override
    public java.lang.String getSerializeType() {
      return instance.getSerializeType();
    }

    /**
     * <code>optional string serializeType = 3;</code>
     * @return The bytes for serializeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSerializeTypeBytes() {
      return instance.getSerializeTypeBytes();
    }

    /**
     * <code>optional string serializeType = 3;</code>
     * @param value The serializeType to set.
     * @return This builder for chaining.
     */
    public Builder setSerializeType(java.lang.String value) {
      copyOnWrite();
      instance.setSerializeType(value);
      return this;
    }

    /**
     * <code>optional string serializeType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerializeType() {
      copyOnWrite();
      instance.clearSerializeType();
      return this;
    }

    /**
     * <code>optional string serializeType = 3;</code>
     * @param value The bytes for serializeType to set.
     * @return This builder for chaining.
     */
    public Builder setSerializeTypeBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSerializeTypeBytes(value);
      return this;
    }

    /**
     * <code>optional string fileContent = 4;</code>
     * @return Whether the fileContent field is set.
     */
    @java.lang.Override
    public boolean hasFileContent() {
      return instance.hasFileContent();
    }

    /**
     * <code>optional string fileContent = 4;</code>
     * @return The fileContent.
     */
    @java.lang.Override
    public java.lang.String getFileContent() {
      return instance.getFileContent();
    }

    /**
     * <code>optional string fileContent = 4;</code>
     * @return The bytes for fileContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFileContentBytes() {
      return instance.getFileContentBytes();
    }

    /**
     * <code>optional string fileContent = 4;</code>
     * @param value The fileContent to set.
     * @return This builder for chaining.
     */
    public Builder setFileContent(java.lang.String value) {
      copyOnWrite();
      instance.setFileContent(value);
      return this;
    }

    /**
     * <code>optional string fileContent = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileContent() {
      copyOnWrite();
      instance.clearFileContent();
      return this;
    }

    /**
     * <code>optional string fileContent = 4;</code>
     * @param value The bytes for fileContent to set.
     * @return This builder for chaining.
     */
    public Builder setFileContentBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFileContentBytes(value);
      return this;
    }

    /**
     * <code>optional float date_created = 5;</code>
     * @return Whether the dateCreated field is set.
     */
    @java.lang.Override
    public boolean hasDateCreated() {
      return instance.hasDateCreated();
    }

    /**
     * <code>optional float date_created = 5;</code>
     * @return The dateCreated.
     */
    @java.lang.Override
    public float getDateCreated() {
      return instance.getDateCreated();
    }

    /**
     * <code>optional float date_created = 5;</code>
     * @param value The dateCreated to set.
     * @return This builder for chaining.
     */
    public Builder setDateCreated(float value) {
      copyOnWrite();
      instance.setDateCreated(value);
      return this;
    }

    /**
     * <code>optional float date_created = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateCreated() {
      copyOnWrite();
      instance.clearDateCreated();
      return this;
    }

    /**
     * <code>optional float date_updated = 6;</code>
     * @return Whether the dateUpdated field is set.
     */
    @java.lang.Override
    public boolean hasDateUpdated() {
      return instance.hasDateUpdated();
    }

    /**
     * <code>optional float date_updated = 6;</code>
     * @return The dateUpdated.
     */
    @java.lang.Override
    public float getDateUpdated() {
      return instance.getDateUpdated();
    }

    /**
     * <code>optional float date_updated = 6;</code>
     * @param value The dateUpdated to set.
     * @return This builder for chaining.
     */
    public Builder setDateUpdated(float value) {
      copyOnWrite();
      instance.setDateUpdated(value);
      return this;
    }

    /**
     * <code>optional float date_updated = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateUpdated() {
      copyOnWrite();
      instance.clearDateUpdated();
      return this;
    }
    // @@protoc_insertion_point(builder_scope:com.innoscripta.common.FileStructure)
  }

  private byte memoizedIsInitialized = 2;

  @java.lang.Override
  @java.lang.SuppressWarnings({ "unchecked", "fallthrough" })
  protected final java.lang.Object dynamicMethod(
    com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
    java.lang.Object arg0,
    java.lang.Object arg1
  ) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.innoscripta.common.protos.file.structure.FileStructure();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "id_",
            "filePath_",
            "serializeType_",
            "fileContent_",
            "dateCreated_",
            "dateUpdated_",
          };
          java.lang.String info =
            "\u0001\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0000\u0001\u0001\u150b\u0000\u0002" +
            "\u1008\u0001\u0003\u1008\u0002\u0004\u1008\u0003\u0005\u1001\u0004\u0006\u1001\u0005" +
            "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
      // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.innoscripta.common.protos.file.structure.FileStructure> parser =
            PARSER;
          if (parser == null) {
            synchronized (
              com.innoscripta.common.protos.file.structure.FileStructure.class
            ) {
              parser = PARSER;
              if (parser == null) {
                parser =
                  new DefaultInstanceBasedParser<com.innoscripta.common.protos.file.structure.FileStructure>(
                    DEFAULT_INSTANCE
                  );
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return memoizedIsInitialized;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:com.innoscripta.common.FileStructure)
  private static final com.innoscripta.common.protos.file.structure.FileStructure DEFAULT_INSTANCE;

  static {
    FileStructure defaultInstance = new FileStructure();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FileStructure.class,
      defaultInstance
    );
  }

  public static com.innoscripta.common.protos.file.structure.FileStructure getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FileStructure> PARSER;

  public static com.google.protobuf.Parser<FileStructure> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
