// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.structure.proto

package com.innoscripta.common.protos.file.structure;

public interface FileStructureOrBuilder
  extends
    // @@protoc_insertion_point(interface_extends:com.innoscripta.common.FileStructure)
    com.google.protobuf.MessageLiteOrBuilder {
  /**
   * <code>required uint32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional string filePath = 2;</code>
   * @return Whether the filePath field is set.
   */
  boolean hasFilePath();
  /**
   * <code>optional string filePath = 2;</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>optional string filePath = 2;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString getFilePathBytes();

  /**
   * <code>optional string serializeType = 3;</code>
   * @return Whether the serializeType field is set.
   */
  boolean hasSerializeType();
  /**
   * <code>optional string serializeType = 3;</code>
   * @return The serializeType.
   */
  java.lang.String getSerializeType();
  /**
   * <code>optional string serializeType = 3;</code>
   * @return The bytes for serializeType.
   */
  com.google.protobuf.ByteString getSerializeTypeBytes();

  /**
   * <code>optional string fileContent = 4;</code>
   * @return Whether the fileContent field is set.
   */
  boolean hasFileContent();
  /**
   * <code>optional string fileContent = 4;</code>
   * @return The fileContent.
   */
  java.lang.String getFileContent();
  /**
   * <code>optional string fileContent = 4;</code>
   * @return The bytes for fileContent.
   */
  com.google.protobuf.ByteString getFileContentBytes();

  /**
   * <code>optional float date_created = 5;</code>
   * @return Whether the dateCreated field is set.
   */
  boolean hasDateCreated();
  /**
   * <code>optional float date_created = 5;</code>
   * @return The dateCreated.
   */
  float getDateCreated();

  /**
   * <code>optional float date_updated = 6;</code>
   * @return Whether the dateUpdated field is set.
   */
  boolean hasDateUpdated();
  /**
   * <code>optional float date_updated = 6;</code>
   * @return The dateUpdated.
   */
  float getDateUpdated();
}
