---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: default
  name: elasticsearch
  labels:
    app: elasticsearch-elastic
spec:
  version: 7.14.0
  nodeSets:
    - name: hot
      count: 3
      config:
        node.attr.data: hot
      podTemplate:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        elasticsearch.k8s.elastic.co/cluster-name: quickstart
                    topologyKey: kubernetes.io/hostname
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Ti
          storageClassName: local-storage
    - name: warm
      count: 3
      config:
        node.attr.data: warm
      podTemplate:
        spec:
        containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 16Gi
                cpu: 2
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: beta.kubernetes.io/instance-type
                      operator: In
                      values:
                        - highstorage
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Ti
            storageClassName: local-storage
---

