// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.status.proto

package com.innoscripta.common.protos.file.status;

public final class FileStatusProtos {

  private FileStatusProtos() {}

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistryLite registry
  ) {}

  static {}
  // @@protoc_insertion_point(outer_class_scope)
}
