// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.status.proto

package com.innoscripta.common.protos.file.status;

public interface FileStatusOrBuilder
  extends
    // @@protoc_insertion_point(interface_extends:com.innoscripta.common.FileStatus)
    com.google.protobuf.MessageLiteOrBuilder {
  /**
   * <code>required uint32 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional string uuid = 2;</code>
   * @return Whether the uuid field is set.
   */
  boolean hasUuid();
  /**
   * <code>optional string uuid = 2;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>optional string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString getUuidBytes();

  /**
   * <code>optional float date_created = 3;</code>
   * @return Whether the dateCreated field is set.
   */
  boolean hasDateCreated();
  /**
   * <code>optional float date_created = 3;</code>
   * @return The dateCreated.
   */
  float getDateCreated();

  /**
   * <code>optional float date_updated = 4;</code>
   * @return Whether the dateUpdated field is set.
   */
  boolean hasDateUpdated();
  /**
   * <code>optional float date_updated = 4;</code>
   * @return The dateUpdated.
   */
  float getDateUpdated();
}
