// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.status.proto

package com.innoscripta.common.protos.file.status;

/**
 * Protobuf type {@code com.innoscripta.common.FileStatus}
 */
public final class FileStatus
  extends com.google.protobuf.GeneratedMessageLite<FileStatus, FileStatus.Builder>
  implements
    // @@protoc_insertion_point(message_implements:com.innoscripta.common.FileStatus)
    FileStatusOrBuilder {

  private FileStatus() {
    uuid_ = "";
  }

  /**
   * Protobuf enum {@code com.innoscripta.common.FileStatus.mimeType}
   */
  public enum mimeType implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>applicationPdf = 0;</code>
     */
    applicationPdf(0),
    /**
     * <code>imagePng = 1;</code>
     */
    imagePng(1),
    /**
     * <code>imageJpeg = 2;</code>
     */
    imageJpeg(2);

    /**
     * <code>applicationPdf = 0;</code>
     */
    public static final int applicationPdf_VALUE = 0;
    /**
     * <code>imagePng = 1;</code>
     */
    public static final int imagePng_VALUE = 1;
    /**
     * <code>imageJpeg = 2;</code>
     */
    public static final int imageJpeg_VALUE = 2;

    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static mimeType valueOf(int value) {
      return forNumber(value);
    }

    public static mimeType forNumber(int value) {
      switch (value) {
        case 0:
          return applicationPdf;
        case 1:
          return imagePng;
        case 2:
          return imageJpeg;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<mimeType> internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<mimeType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<mimeType>() {
      @java.lang.Override
      public mimeType findValueByNumber(int number) {
        return mimeType.forNumber(number);
      }
    };

    public static com.google.protobuf.Internal.EnumVerifier internalGetVerifier() {
      return mimeTypeVerifier.INSTANCE;
    }

    private static final class mimeTypeVerifier
      implements com.google.protobuf.Internal.EnumVerifier {

      static final com.google.protobuf.Internal.EnumVerifier INSTANCE = new mimeTypeVerifier();

      @java.lang.Override
      public boolean isInRange(int number) {
        return mimeType.forNumber(number) != null;
      }
    }

    private final int value;

    private mimeType(int value) {
      this.value = value;
    }
    // @@protoc_insertion_point(enum_scope:com.innoscripta.common.FileStatus.mimeType)
  }

  /**
   * Protobuf enum {@code com.innoscripta.common.FileStatus.statusType}
   */
  public enum statusType implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>FAILURE = 1;</code>
     */
    FAILURE(1),
    /**
     * <code>PENDING = 2;</code>
     */
    PENDING(2);

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>FAILURE = 1;</code>
     */
    public static final int FAILURE_VALUE = 1;
    /**
     * <code>PENDING = 2;</code>
     */
    public static final int PENDING_VALUE = 2;

    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static statusType valueOf(int value) {
      return forNumber(value);
    }

    public static statusType forNumber(int value) {
      switch (value) {
        case 0:
          return SUCCESS;
        case 1:
          return FAILURE;
        case 2:
          return PENDING;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<statusType> internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<statusType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<statusType>() {
      @java.lang.Override
      public statusType findValueByNumber(int number) {
        return statusType.forNumber(number);
      }
    };

    public static com.google.protobuf.Internal.EnumVerifier internalGetVerifier() {
      return statusTypeVerifier.INSTANCE;
    }

    private static final class statusTypeVerifier
      implements com.google.protobuf.Internal.EnumVerifier {

      static final com.google.protobuf.Internal.EnumVerifier INSTANCE = new statusTypeVerifier();

      @java.lang.Override
      public boolean isInRange(int number) {
        return statusType.forNumber(number) != null;
      }
    }

    private final int value;

    private statusType(int value) {
      this.value = value;
    }
    // @@protoc_insertion_point(enum_scope:com.innoscripta.common.FileStatus.statusType)
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;

  /**
   * <code>required uint32 id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>required uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  /**
   * <code>required uint32 id = 1;</code>
   * @param value The id to set.
   */
  private void setId(int value) {
    bitField0_ |= 0x00000001;
    id_ = value;
  }

  /**
   * <code>required uint32 id = 1;</code>
   */
  private void clearId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    id_ = 0;
  }

  public static final int UUID_FIELD_NUMBER = 2;
  private java.lang.String uuid_;

  /**
   * <code>optional string uuid = 2;</code>
   * @return Whether the uuid field is set.
   */
  @java.lang.Override
  public boolean hasUuid() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>optional string uuid = 2;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    return uuid_;
  }

  /**
   * <code>optional string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getUuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uuid_);
  }

  /**
   * <code>optional string uuid = 2;</code>
   * @param value The uuid to set.
   */
  private void setUuid(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
    bitField0_ |= 0x00000002;
    uuid_ = value;
  }

  /**
   * <code>optional string uuid = 2;</code>
   */
  private void clearUuid() {
    bitField0_ = (bitField0_ & ~0x00000002);
    uuid_ = getDefaultInstance().getUuid();
  }

  /**
   * <code>optional string uuid = 2;</code>
   * @param value The bytes for uuid to set.
   */
  private void setUuidBytes(com.google.protobuf.ByteString value) {
    uuid_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int DATE_CREATED_FIELD_NUMBER = 3;
  private float dateCreated_;

  /**
   * <code>optional float date_created = 3;</code>
   * @return Whether the dateCreated field is set.
   */
  @java.lang.Override
  public boolean hasDateCreated() {
    return ((bitField0_ & 0x00000004) != 0);
  }

  /**
   * <code>optional float date_created = 3;</code>
   * @return The dateCreated.
   */
  @java.lang.Override
  public float getDateCreated() {
    return dateCreated_;
  }

  /**
   * <code>optional float date_created = 3;</code>
   * @param value The dateCreated to set.
   */
  private void setDateCreated(float value) {
    bitField0_ |= 0x00000004;
    dateCreated_ = value;
  }

  /**
   * <code>optional float date_created = 3;</code>
   */
  private void clearDateCreated() {
    bitField0_ = (bitField0_ & ~0x00000004);
    dateCreated_ = 0F;
  }

  public static final int DATE_UPDATED_FIELD_NUMBER = 4;
  private float dateUpdated_;

  /**
   * <code>optional float date_updated = 4;</code>
   * @return Whether the dateUpdated field is set.
   */
  @java.lang.Override
  public boolean hasDateUpdated() {
    return ((bitField0_ & 0x00000008) != 0);
  }

  /**
   * <code>optional float date_updated = 4;</code>
   * @return The dateUpdated.
   */
  @java.lang.Override
  public float getDateUpdated() {
    return dateUpdated_;
  }

  /**
   * <code>optional float date_updated = 4;</code>
   * @param value The dateUpdated to set.
   */
  private void setDateUpdated(float value) {
    bitField0_ |= 0x00000008;
    dateUpdated_ = value;
  }

  /**
   * <code>optional float date_updated = 4;</code>
   */
  private void clearDateUpdated() {
    bitField0_ = (bitField0_ & ~0x00000008);
    dateUpdated_ = 0F;
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    java.nio.ByteBuffer data
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    java.nio.ByteBuffer data,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    com.google.protobuf.ByteString data
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    com.google.protobuf.ByteString data,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    byte[] data
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    byte[] data,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      data,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    java.io.InputStream input
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    java.io.InputStream input,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input,
      extensionRegistry
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseDelimitedFrom(
    java.io.InputStream input
  ) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseDelimitedFrom(
    java.io.InputStream input,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    com.google.protobuf.CodedInputStream input
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus parseFrom(
    com.google.protobuf.CodedInputStream input,
    com.google.protobuf.ExtensionRegistryLite extensionRegistry
  ) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
      DEFAULT_INSTANCE,
      input,
      extensionRegistry
    );
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(
    com.innoscripta.common.protos.file.status.FileStatus prototype
  ) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.innoscripta.common.FileStatus}
   */
  public static final class Builder
    extends com.google.protobuf.GeneratedMessageLite.Builder<com.innoscripta.common.protos.file.status.FileStatus, Builder>
    implements
      // @@protoc_insertion_point(builder_implements:com.innoscripta.common.FileStatus)
      com.innoscripta.common.protos.file.status.FileStatusOrBuilder {

    // Construct using com.innoscripta.common.protos.file.status.FileStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return instance.hasId();
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return instance.getId();
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }

    /**
     * <code>required uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>optional string uuid = 2;</code>
     * @return Whether the uuid field is set.
     */
    @java.lang.Override
    public boolean hasUuid() {
      return instance.hasUuid();
    }

    /**
     * <code>optional string uuid = 2;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      return instance.getUuid();
    }

    /**
     * <code>optional string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUuidBytes() {
      return instance.getUuidBytes();
    }

    /**
     * <code>optional string uuid = 2;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(java.lang.String value) {
      copyOnWrite();
      instance.setUuid(value);
      return this;
    }

    /**
     * <code>optional string uuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      copyOnWrite();
      instance.clearUuid();
      return this;
    }

    /**
     * <code>optional string uuid = 2;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUuidBytes(value);
      return this;
    }

    /**
     * <code>optional float date_created = 3;</code>
     * @return Whether the dateCreated field is set.
     */
    @java.lang.Override
    public boolean hasDateCreated() {
      return instance.hasDateCreated();
    }

    /**
     * <code>optional float date_created = 3;</code>
     * @return The dateCreated.
     */
    @java.lang.Override
    public float getDateCreated() {
      return instance.getDateCreated();
    }

    /**
     * <code>optional float date_created = 3;</code>
     * @param value The dateCreated to set.
     * @return This builder for chaining.
     */
    public Builder setDateCreated(float value) {
      copyOnWrite();
      instance.setDateCreated(value);
      return this;
    }

    /**
     * <code>optional float date_created = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateCreated() {
      copyOnWrite();
      instance.clearDateCreated();
      return this;
    }

    /**
     * <code>optional float date_updated = 4;</code>
     * @return Whether the dateUpdated field is set.
     */
    @java.lang.Override
    public boolean hasDateUpdated() {
      return instance.hasDateUpdated();
    }

    /**
     * <code>optional float date_updated = 4;</code>
     * @return The dateUpdated.
     */
    @java.lang.Override
    public float getDateUpdated() {
      return instance.getDateUpdated();
    }

    /**
     * <code>optional float date_updated = 4;</code>
     * @param value The dateUpdated to set.
     * @return This builder for chaining.
     */
    public Builder setDateUpdated(float value) {
      copyOnWrite();
      instance.setDateUpdated(value);
      return this;
    }

    /**
     * <code>optional float date_updated = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateUpdated() {
      copyOnWrite();
      instance.clearDateUpdated();
      return this;
    }
    // @@protoc_insertion_point(builder_scope:com.innoscripta.common.FileStatus)
  }

  private byte memoizedIsInitialized = 2;

  @java.lang.Override
  @java.lang.SuppressWarnings({ "unchecked", "fallthrough" })
  protected final java.lang.Object dynamicMethod(
    com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
    java.lang.Object arg0,
    java.lang.Object arg1
  ) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.innoscripta.common.protos.file.status.FileStatus();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "id_",
            "uuid_",
            "dateCreated_",
            "dateUpdated_",
          };
          java.lang.String info =
            "\u0001\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0001\u0001\u150b\u0000\u0002" +
            "\u1008\u0001\u0003\u1001\u0002\u0004\u1001\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
      // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.innoscripta.common.protos.file.status.FileStatus> parser =
            PARSER;
          if (parser == null) {
            synchronized (
              com.innoscripta.common.protos.file.status.FileStatus.class
            ) {
              parser = PARSER;
              if (parser == null) {
                parser =
                  new DefaultInstanceBasedParser<com.innoscripta.common.protos.file.status.FileStatus>(
                    DEFAULT_INSTANCE
                  );
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return memoizedIsInitialized;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:com.innoscripta.common.FileStatus)
  private static final com.innoscripta.common.protos.file.status.FileStatus DEFAULT_INSTANCE;

  static {
    FileStatus defaultInstance = new FileStatus();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FileStatus.class,
      defaultInstance
    );
  }

  public static com.innoscripta.common.protos.file.status.FileStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FileStatus> PARSER;

  public static com.google.protobuf.Parser<FileStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
